### ISSUE TITLE
Casos de teste para validar aplicação

### ISSUE THREAD

**Issue by rafast** [rafast/ClinicaSorriso#4]
### Cadastro de paciente
- Cadastrar paciente com CPF inválido []
- Cadastrar paciente com nome com menos de 5 caracteres []
- Cadastrar paciente com data de nascimento fora do formato DD/MM/AAAA []
- Cadastrar paciente com CPF já cadastrado []
- Cadastrar paciente com idade inferior a 13 anos []

### Exclusão de paciente
- Excluir paciente com CPF não cadastrado []
- Excluir paciente com consulta agendada futura, e verificar listagem da agenda e conferir se a consulta foi excluída com sucesso []
- Excluir paciente com consulta agendada passada e verificar se a mesma também foi excluída []

### Agendamento de consultas
- Agendar consulta com CPF não cadastrado []
- Agendar consulta com data da consulta fora do formato DD/MM/AAAA []
- Agendar consulta com Hora Inicial e Final fora do formato HHMM []
- Agendar consulta com data da consulta anterior a data atual []
- Agendar consulta com data da consulta pro mesmo dia, com hora inicial anterior a hora atual []
- Agendar consulta com data da consulta pro mesmo dia, com hora inicial posterior a hora atual []
- Agendar consulta com Hora final maior que Hora Inicial []
- Agendar consulta para um paciente com agendamento futuro []
- Agendar consulta para um horário já preenchido por outra consulta []
- Agendar consulta com horário inicial e final fora do padrão de 15 minutos de intervalo []
- Agendar consulta fora do horário de expediente do consultório (08:00 às 19:00) []

### Exclusão de consultas
- Cancelar consulta com data inicio menor que a data atual []
- Cancelar consulta com data inicio igual a data do dia e hora inicio menor que hora atual []
- Cancelar consulta futura, e depois listar os pacientes verificando que a sua consulta foi devidamente cancelada []

### Listagem agenda
- Listar agenda por período com data inicial e final fora do formato DD/MM/AAAA []

**Comment by rafast** [comment]
Cadastro e Exclusão de Paciente testados com sucesso!

**Comment by LucasbernardinoLa** [comment]
Agendamento e Exclusão de Consulta testados e funcionando!

**Comment by rafast** [comment]
Todos os testes realizados com sucesso!
